# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: 
  - name: HFTransformersNLP
      # Name of the language model to use
    model_name: "bert"
    # Pre-Trained weights to be loaded
    model_weights: "bert-base-uncased"
  - name: LanguageModelTokenizer
    # Flag to check whether to split intents
    intent_tokenization_flag: False
  # Symbol on which intent should be split
    intent_split_symbol: "_"
  - name: LanguageModelFeaturizer
  - name: DIETClassifier
    similarity_type: cosine
    loss_type: softmax
    transformer_size: 256 # No of units trasformer
    epochs: 100
    evaluate_on_number_of_examples: 0
    evaluate_every_number_of_epochs: 20
    batch_size: [64, 256]
    tensorboard_log_directory: "./tensorboard/en/"
    tensorboard_log_level: "epoch"
  - name: EntitySynonymMapper
  # - name: ResponseSelector
  #   epochs: 100


# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: TEDPolicy # KerasPolicy is deprecated
    max_history: 10
    epochs: 100
    evaluate_on_number_of_examples: 0
    evaluate_every_number_of_epochs: 5
    tensorboard_log_directory: "./tensorboard/en/"
    tensorboard_log_level: "epoch"
  # - name: FallbackPolicy #Testing
  #   nlu_threshold: 0.01
  #   core_threshold: 0.01
  #   fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy
  - name: MappingPolicy
  # - name: TwoStageFallbackPolicy
